#!/bin/bash -e

. settings

for repo in $(./ensure_clean_git_checkouts "$@") ; do
	(
		cd "$GIT_DIR/$repo"
		git fetch --quiet "$GIT_REMOTE"
		git checkout -b "$GIT_STABLE_BRANCH" "${GIT_REMOTE}/${GIT_DEVELOP_BRANCH}"

		if [[ $repo == foreman-installer ]]; then
			if ! bundle check &>/dev/null; then
				echo "Bundle dependencies not installed in foreman-installer" >&2
				echo "Run: cd $GIT_DIR/$repo && bundle install" >&2
				exit 1
			fi
			bundle exec rake pin_modules
			sed -i '/Puppetfile.lock/d' .gitignore
			bundle exec librarian-puppet install
			git add .gitignore Puppetfile*
			git commit --message "Pin Puppet modules for ${VERSION}"
		elif [[ $repo == candlepin-packaging ]] ; then
			sed -i "/candlepin_version/ s/'.\+'/'$VERSION'/" package_manifest.yaml
			git add package_manifest.yaml
			git commit --message "Set Candlepin version to ${VERSION}"
		fi
	)
done
