#!/bin/bash -e

. settings

for repo in $(./ensure_clean_git_checkouts "$@") ; do
	(
		cd "$GIT_DIR/$repo"
		git fetch --quiet "$GIT_REMOTE"
		git checkout -b "$GIT_STABLE_BRANCH" "${GIT_REMOTE}/${GIT_DEVELOP_BRANCH}"

		if [[ $repo == foreman-installer ]]; then
			bundle exec rake pin_modules
			sed -i '/Puppetfile.lock/d' .gitignore
			bundle exec librarian-puppet install
			git add .gitignore Puppetfile*
			git commit --message "Pin Puppet modules for ${VERSION}"
		fi
	)
done
