#!/bin/bash -e

. settings

require_fullversion

FLAVOR=$1

if [[ $FLAVOR != deb ]] && [[ $FLAVOR != rpm ]] ; then
	echo "Usage: $0 [deb|rpm]" >&2
	exit 1
fi

REMOTE_BRANCH="${FLAVOR}/${FOREMAN_VERSION}"
FULL_REMOTE_BRANCH="$PACKAGING_GIT_REMOTE/$REMOTE_BRANCH"
FEATURE_BRANCH="${FLAVOR}/release-$PROJECT-$FULLVERSION"

if [[ $GIT_USE_WORKTREES == true ]] ; then
	RELEASE_PACKAGING_DIR="${PACKAGING_DIR}/${FLAVOR}-$VERSION"

	if [[ ! -d "$RELEASE_PACKAGING_DIR" ]] ; then
		(
			cd "${PACKAGING_DIR}/master"
			git worktree add "$RELEASE_PACKAGING_DIR" "$PACKAGING_GIT_REMOTE/$REMOTE_BRANCH"
		)
	fi
else
	RELEASE_PACKAGING_DIR="${PACKAGING_DIR}"

	if [[ ! -d "$RELEASE_PACKAGING_DIR" ]] ; then
		git clone --quiet --origin "$PACKAGING_GIT_REMOTE" "$(github_url foreman-packaging)" "${RELEASE_PACKAGING_DIR}"
	fi
fi

cd "$RELEASE_PACKAGING_DIR"

git fetch $PACKAGING_GIT_REMOTE
git checkout -b "${FEATURE_BRANCH}" "${FULL_REMOTE_BRANCH}"

if [[ $FLAVOR == deb ]] ; then
	scripts/changelog.rb -v "${FULLVERSION/-rc/~rc}-1" -m "$FULLVERSION released" debian/*/*/changelog
	git add debian/*/*/changelog
else
	if [[ $FULLVERSION == *-rc* ]]; then
		PRERELEASE=${FULLVERSION##*-}
		obal update --version "${FULLVERSION%%-rc*}" --prerelease "${PRERELEASE}" --release keep "${RPM_PACKAGES[@]}"
	else
		obal update --version "${FULLVERSION}" "${RPM_PACKAGES[@]}"
	fi

	git add "${RPM_PACKAGES[@]/#/packages\/${PROJECT}/}"
fi

git commit -m "Release $FULLVERSION"

if [[ $PACKAGING_PR == true ]] ; then
	# Ensure fork exists with configured remote name
	GH_PROMPT_DISABLED=1 gh repo fork theforeman/foreman-packaging --remote-name "$PACKAGING_FORK_REMOTE"

	git push --set-upstream "$PACKAGING_FORK_REMOTE" HEAD

	gh pr create --repo theforeman/foreman-packaging \
	             --title "${FLAVOR^^}: Release ${PROJECT^} $FULLVERSION" \
	             --head "$GITHUB_USER:$FEATURE_BRANCH" \
	             --base "$REMOTE_BRANCH" \
	             --body "Release ${PROJECT^} $FULLVERSION"
else
	git push "$PACKAGING_GIT_REMOTE" "HEAD:$REMOTE_BRANCH"
fi
