#!/bin/bash -e

. settings

# Accept optional version argument, otherwise use FULLVERSION from settings
if [[ -n $1 ]]; then
	VERSION_NAME="$1"
else
	require_fullversion
	# Strip any -rc or other suffix from FULLVERSION to get base version (e.g., 3.18.0-rc1 -> 3.18.0)
	VERSION_NAME="${FULLVERSION%%-*}"
fi

if [[ -z $REDMINE_API_KEY ]] ; then
	echo "No API key set. Get it from https://projects.theforeman.org/my/account"
	read -s -r -p "Redmine API KEY: " REDMINE_API_KEY
fi
export REDMINE_API_KEY

./redmine version create "$PROJECT" "$VERSION_NAME" --status open --sharing descendants
