#!/bin/bash -e

. settings

./ensure_clean_git_checkouts tool_belt > /dev/null

TOOL_BELT="${GIT_DIR}/tool_belt"
CONFIG_DIR="${TOOL_BELT}/configs/${PROJECT}"
OUTPUT_FILE="${CONFIG_DIR}/${VERSION}.yaml"
OUTPUT_DIR="${TOOL_BELT}/mash_scripts/${PROJECT}/${VERSION}.0"

(
	if [[ $PROJECT == katello ]] ; then
		sed "s/\(foreman\(-plugins\)\?\)-nightly/\1-${FOREMAN_VERSION}/" "${CONFIG_DIR}/nightly.yaml"
	else
		cat "${CONFIG_DIR}/nightly.yaml"
	fi | ./build_tool_belt_config "$VERSION" "$GPGKEY" "$PROJECT"
) > "${OUTPUT_FILE}"

cd "${TOOL_BELT}"

git fetch --quiet "${GIT_REMOTE}"
git checkout -b "mash-${PROJECT}-${VERSION}" "${GIT_REMOTE}/master"

./tools.rb mash-scripts "${OUTPUT_FILE}"

if [[ $PROJECT == foreman ]] ; then
	sed -i '/strict_keys/ s/True/False/' "${OUTPUT_DIR}/foreman-plugins-${VERSION}"-*.mash
fi

git add "${OUTPUT_FILE}" "${OUTPUT_DIR}"
