#!/bin/bash -e

. settings

MAJOR=${VERSION%.*}
MINOR=${VERSION#*.}
DEVELOP=${MAJOR}.$((MINOR + 1))
DEVELOP_VERSION="${DEVELOP}.0-develop"

for project in $(./ensure_clean_git_checkouts "$@") ; do
	(
		cd "$GIT_DIR/$project"
		git checkout "$GIT_DEVELOP_BRANCH"
		git pull --quiet

		if [[ $project == katello ]] ; then
			sed -i '/VERSION/ s/[0-9]\+\.[0-9]\+\.[0-9]\+/'"${DEVELOP}".0'/' lib/katello/version.rb
		else
			echo "${DEVELOP}.0-develop" > VERSION
			git add VERSION
		fi

		if [[ $project == foreman ]] ; then
			sed -i '/"version": "/ s/"[0-9]\+\.[0-9]\+\.[0-9]\+"/"'"${DEVELOP}".0'"/' package.json
			git add package.json
		fi

		git commit --message "Bump ${GIT_DEVELOP_BRANCH} to ${DEVELOP_VERSION}"
		git tag --message "Start ${DEVELOP} development" "${DEVELOP_VERSION}"
	)
done
