#!/bin/bash -e

. settings

if [[ -z $1 ]] ; then
	PROJECTS=$TAR_PROJECTS
else
	PROJECTS=$*
fi

PROJECTS=${PROJECTS/foreman-proxy/smart-proxy}

for project in $PROJECTS ; do
	(
		project_dir="$GIT_DIR/$project"
		if [[ -d "$project_dir" ]] ; then
			cd "$project_dir"
			if ! git diff --quiet --exit-code ; then
				echo "Checkout in $PWD is dirty"
				exit 1
			fi
		else
			git clone --quiet -o "$GIT_REMOTE" "https://github.com/theforeman/${project}" "${project_dir}"
		fi
	)
done

echo "$PROJECTS"
