#!/bin/bash -e

. settings

if [[ -z $1 ]] ; then
	REPOS=$TAR_PROJECTS
else
	REPOS=$*
fi

REPOS=${REPOS/foreman-proxy/smart-proxy}

for repo in $REPOS ; do
	(
		project_dir="$GIT_DIR/$repo"
		if [[ -d "$project_dir" ]] ; then
			cd "$project_dir"
			if ! git diff --quiet --exit-code ; then
				echo "Checkout in $PWD is dirty" >&2
				exit 1
			fi
		else
			git clone --quiet -o "$GIT_REMOTE" "https://github.com/${GITHUB_NAMESPACE}/${repo}" "${project_dir}"
		fi
	)
done

echo "$REPOS"
