#!/bin/bash -e

. settings

require_gpg_key

# Verify key has no third-party signatures
./verify_gpg_clean || exit $?

if [[ $1 == "force" ]] ; then
	FORCE="--force"
else
	FORCE=""
fi

gpg_with_password --batch --homedir "$KEYDIR" --export-secret-keys -a "$FULLGPGKEY" | gopass insert --multiline $FORCE "$PASS_NAME_KEY"

gopass_sync
