#!/bin/bash -e

. settings

if [[ ! -d $KEYDIR ]] ; then
	echo "Keydir $KEYDIR doesn't exist"
	exit 1
fi

if [[ -z $FULLGPGKEY ]] ; then
	echo "FULLGPGKEY must be set"
	gpg2 --homedir "$KEYDIR" --list-key "$SIGNER"
	exit 2
fi

# Verify key has no third-party signatures
./verify_gpg_clean || exit $?

if [[ $1 == "force" ]] ; then
	FORCE="--force"
else
	FORCE=""
fi

gpg_with_password --batch --homedir "$KEYDIR" --export-secret-keys -a "$FULLGPGKEY" | gopass insert --multiline $FORCE "$PASS_NAME_KEY"

gopass_sync
