#!/bin/bash -e

. settings

require_pass_name_key

if [[ ! -d "$KEYDIR" ]] ; then
	mkdir -p -m 0700 "$KEYDIR"
fi

gopass show "$PASS_NAME_KEY" | gpg_with_password --batch --homedir "$KEYDIR" --import
