#!/bin/bash -e

. settings

TARGET_DATE="$1"
OWNER="$2"
ENGINEER="$3"

if [[ -z $TARGET_DATE ]] ; then
	read -r -p "Target date (YYYY-MM-DD): " TARGET_DATE
	READ=1
fi
if [[ -z $OWNER ]] ; then
	read -r -p "Release owner (Discourse username): " OWNER
	READ=1
fi
if [[ -z $ENGINEER ]] ; then
	read -r -p "Release engineer (Discourse username): " ENGINEER
	READ=1
fi
if [[ $READ == 1 ]] ; then
	echo >&2
fi

if [[ "$PROJECT" == katello && -z "$FOREMAN_VERSION" ]]; then
	echo "FOREMAN_VERSION must be set to a real version in $RELEASEDIR/settings when generating a Katello branch procedure" >&2
	exit 1
fi

FOREMAN_VERSION_ARGS=()
if [[ "$PROJECT" == katello ]]; then
	FOREMAN_VERSION_ARGS=(--foreman-version "$FOREMAN_VERSION")
fi

./procedure branch --project "$PROJECT" --release "$VERSION" "${FOREMAN_VERSION_ARGS[@]}" --target-date "$TARGET_DATE" --owner "$OWNER" --engineer "$ENGINEER"
