#!/bin/bash

set -e

. settings

require_gpg_key

for os in $OSES; do
  for arch in $ARCHES; do
    UNSIGNED_RPMS=$(./list_unsigned_rpms "$STAGE_LOCAL_BASE/$os/$arch" "$HALFGPGKEY")

    if [[ -n "$UNSIGNED_RPMS" ]]; then
      echo "$UNSIGNED_RPMS" | xargs ./sign_rpms
      createrepo_c --general-compress-type gz --database --update "$STAGE_LOCAL_BASE/$os/$arch"
    fi
  done
done
