#!/bin/bash

set -e

. settings

ARCHES="x86_64 source"

for os in $OSES; do
  BASE="tmp/$PROJECT/$VERSION/$os"

  for arch in $ARCHES; do
    UNSIGNED_RPMS=$(./list_unsigned_rpms "$BASE/$arch" "$HALFGPGKEY")

    if [[ -n "$UNSIGNED_RPMS" ]]; then
      echo "$UNSIGNED_RPMS" | xargs ./sign_rpms
      createrepo_c --update "$BASE/$arch"
    fi
  done
done
