#!/bin/bash -e

. settings

require_gpg_key

gpg2 --homedir "$KEYDIR" --armor --export "$FULLGPGKEY" | gpg2 --import

echo ""
echo "Opening GPG to sign the key"
echo ""
echo "Use fpr to see the fingerprint"
echo "Use sign to sign the new key"
echo ""
echo "https://projects.theforeman.org/projects/foreman/wiki/GPG_Keys"
echo ""

gpg2 --edit-key "$FULLGPGKEY"
