#!/bin/bash -e

. settings

if [[ -z $1 ]] ; then
	PROJECTS=$TAR_PROJECTS
else
	PROJECTS=$*
fi

PROJECTS=${PROJECTS/foreman-proxy/smart-proxy}

for project in $PROJECTS ; do
	(
		project_dir="$GIT_DIR/$project"
		if [[ -d "$project_dir" ]] ; then
			cd "$project_dir"
			if ! git diff --quiet --exit-code ; then
				echo "Checkout in $PWD is dirty"
				exit 1
			fi
		else
			git clone -o "$GIT_REMOTE" "https://github.com/theforeman/${project}" "${project_dir}"
		fi
	)
done

for project in $PROJECTS ; do
	(
		cd "$GIT_DIR/$project"
		git checkout "${VERSION}-stable"
		git pull --quiet
		echo "$FULLVERSION" > VERSION
		git commit --quiet --all --message "Release $FULLVERSION"
		if [ -x ./extras/changelog ] ; then
			./extras/changelog
			git commit --amend --quiet --all --no-edit
		fi
		if [ -x ./extra/changelog ] ; then
			./extra/changelog
			git commit --amend --quiet --all --no-edit
		fi
		git tag --sign --message "Release $FULLVERSION" "$FULLVERSION"
		echo "Tagged ${project} ${FULLVERSION}"
	)
done
