#!/bin/bash -e

. settings

for project in $(./ensure_clean_git_checkouts "$@") ; do
	(
		cd "$GIT_DIR/$project"
		echo "Pushing ${project} ${VERSION}-stable"
		git push "${GIT_REMOTE}" "${VERSION}-stable" --follow-tags
	)
done
