#!/bin/bash -e

. settings

for project in $(./ensure_clean_git_checkouts "$@") ; do
	(
		cd "$GIT_DIR/$project"
		git checkout "${VERSION}-stable"
		git pull --quiet
		echo "$FULLVERSION" > VERSION
		git commit --quiet --all --message "Release $FULLVERSION"
		if [ -x ./extras/changelog ] ; then
			./extras/changelog
			git commit --amend --quiet --all --no-edit
		fi
		if [ -x ./extra/changelog ] ; then
			./extra/changelog
			git commit --amend --quiet --all --no-edit
		fi
		git tag --sign --message "Release $FULLVERSION" "$FULLVERSION"
		echo "Tagged ${project} ${FULLVERSION}"
	)
done
