#!/bin/bash -e

. settings

require_fullversion

for project in $(./ensure_clean_git_checkouts "$@") ; do
	(
		cd "$GIT_DIR/$project"
		git fetch --quiet "$GIT_REMOTE"
		git checkout "${GIT_STABLE_BRANCH}"
		git merge --ff-only "${GIT_REMOTE}/${GIT_STABLE_BRANCH}"
		echo "$FULLVERSION" > VERSION
		git commit --quiet --all --message "Release $FULLVERSION"
		if [ -x ./extras/changelog ] ; then
			./extras/changelog
			git commit --amend --quiet --all --no-edit
		fi
		if [ -x ./extra/changelog ] ; then
			./extra/changelog
			git commit --amend --quiet --all --no-edit
		fi
		git tag --sign --message "Release $FULLVERSION" "$FULLVERSION"
		echo "Tagged ${project} ${FULLVERSION}"
	)
done
