#!/bin/bash -e

. settings

if [[ -z $1 ]] ; then
	PROJECTS=$TAR_PROJECTS
else
	PROJECTS=$*
fi

PROJECTS=${PROJECTS/foreman-proxy/smart-proxy}

for project in $PROJECTS ; do
	(
		cd "$GIT_DIR/$project"
		if ! git diff --quiet --exit-code ; then
			echo "Checkout in $PWD is dirty"
			exit 1
		fi
	)
done

for project in $PROJECTS ; do
	(
		cd "$GIT_DIR/$project"
		git checkout "${VERSION}-stable"
		echo "Pushing ${project} ${VERSION}-stable"
		git push "${GIT_REMOTE}" "${VERSION}-stable" --follow-tags
	)
done
