#!/bin/bash -e

. settings

USER='yumrepostage'
HOST='web01.osuosl.theforeman.org'

if [[ "${VERSION}" != "nightly" ]]; then
  ./verify_stage_sigs
fi

rsync --checksum --times --perms --recursive --links --verbose --partial --one-file-system --delete-after "tmp/$PROJECT/$VERSION/" "$USER@$HOST:rsync_cache/$PROJECT/$VERSION/"
