#!/bin/bash -e

. settings

require_gpg_key

upload() {
	local gpg_key
	gpg_key=$(mktemp)
	trap "rm -f $gpg_key" EXIT
	gpg2 --homedir "$KEYDIR" --armor --export "$FULLGPGKEY" > "$gpg_key"

	ansible_playbook --inventory="${RPM_HOST}," --extra-vars="release=${VERSION} gpg_key=${gpg_key} project=${PROJECT}" upload_yum_gpg_public_key.yaml
}

upload
