#!/bin/bash -e

. settings

USER='yumrepostage'

./verify_stage_sigs

rsync --checksum --times --perms --recursive --links --verbose --partial --one-file-system --delete-after "${STAGE_LOCAL_BASE}/" "$USER@$RPM_HOST:rsync_cache/$PROJECT/$VERSION/"
